---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: started
    enabled: yes

- set_fact:
    kibana_etc: /opt/kibana/config
  when: kibana_version | version_compare('5.0', '<')

- set_fact:
    kibana_etc: /etc/kibana
  when: kibana_version | version_compare('5.0', '>=')

- name: Copy Kibana configuration.
  template:
    src: kibana.yml.j2
    dest: "{{ kibana_etc }}/kibana.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart kibana
