---
- name: Ensure dependency is installed (Ubuntu).
  apt: name=apt-transport-https state=present

- name: Add Elasticsearch apt key.
  apt_key:
    url: https://packages.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Kibana repository. - 4.x
  apt_repository:
    repo: 'deb https://packages.elastic.co/kibana/{{ kibana_version }}/debian stable main'
    state: present
    update_cache: yes
  when: kibana_version | version_compare('5.0', '<')

- name: Add Kibana repository 5.x
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/5.x/apt stable main'
    state: present
    update_cache: yes
  when: kibana_version | version_compare('5.0', '>=')

- name: Install Kibana.
  apt: name=kibana{% if kibana_version is defined and kibana_version != "" %}={{ kibana_version }}{% endif %} state=present


